version: "3"

services:
  core:
    build:
      context: .
      dockerfile: "Dockerfile"
    image: s3uploader:latest
    working_dir: /usr/src/uploader
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - .:/usr/src/uploader
    networks:
      dialler_network:
        ipv4_address: 172.28.0.21

networks:
  dialler_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
